In [2]:
from pycaret.datasets import get_data
data1 = get_data(dataset = 'traffic')

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,Rush Hour,traffic_volume
0,NaN,288.28,0.0,0.0,40,Clouds,1,5545
1,NaN,289.36,0.0,0.0,75,Clouds,0,4516
2,NaN,289.58,0.0,0.0,90,Clouds,0,4767
3,NaN,290.13,0.0,0.0,90,Clouds,0,5026
4,NaN,291.14,0.0,0.0,75,Clouds,0,4918

In [3]:
from pycaret.regression import *

In [7]:
dataset = setup(data=data1, target='traffic_volume', session_id=438, verbose=True)

In [8]:
best = compare_models()

In [9]:
tuned_best = tune_model(estimator = best)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [10]:
final_model = finalize_model(estimator = tuned_best)

In [14]:
save_model(final_model, 'rf_base_traffic')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['temp', 'rain_1h', 'snow_1h',
                                              'clouds_all', 'Rush Hour'],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=['holiday', 'weather_main'],
                                     transformer=SimpleImputer(strategy='most_frequent'))),
                 ('onehot_encoding',
                  TransformerWrapper(include=['holiday', 'weather_main'],
                                     transformer=OneHotEncoder(cols=['holiday',
                                                                     'weather_main'],
                                                               handle_missing='return_nan',
                                                               use_cat_names=True))),
                 ('clean_column_names',
                  TransformerWrapper(transformer=CleanColumnNames())),
                 ('actual_estimator',
                  LGBMRegressor(n_jobs=-1, random_state=438))]),
 'rf_base_traffic.pkl')

In [15]:
saved_model = load_model('rf_base_traffic')

Transformation Pipeline and Model Successfully Loaded

In [18]:
new_data = get_data(dataset='traffic').head(100)

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,Rush Hour,traffic_volume
0,NaN,288.28,0.0,0.0,40,Clouds,1,5545
1,NaN,289.36,0.0,0.0,75,Clouds,0,4516
2,NaN,289.58,0.0,0.0,90,Clouds,0,4767
3,NaN,290.13,0.0,0.0,90,Clouds,0,5026
4,NaN,291.14,0.0,0.0,75,Clouds,0,4918

In [19]:
predictions = predict_model(saved_model, data=new_data)
predictions.head()

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,Rush Hour,traffic_volume,prediction_label
0,NaN,288.279999,0.0,0.0,40,Clouds,1,5545,4654.894720
1,NaN,289.359985,0.0,0.0,75,Clouds,0,4516,3324.857894
2,NaN,289.579987,0.0,0.0,90,Clouds,0,4767,3210.764667
3,NaN,290.130005,0.0,0.0,90,Clouds,0,5026,3210.764667
4,NaN,291.140015,0.0,0.0,75,Clouds,0,4918,3375.853883